# application.properties 파일은 항상 resources폴더 아래에 만든다
# 목적 : 스프링 서버가 실행될 떄 설정을 로딩하는 파일
# 주석할 때는 # 사용한다
# 참고 : 상단메뉴 -> 설정 -> '인코딩' 메뉴 클릭

# 1. 내장 AWS PORT(프로그램 식별번호) 번호 변경, 기본값은 8080이며 수정 가능
server.port=8080
# 2. DAO가 아닌 프로퍼티파일에서 DB연동
# 2-1 연동할 db서버 주소
spring.datasource.url=jdbc:mysql://localhost:3306/mydb0313
# 2-2 연동할 db서버 계정/비밀번호, 띄어쓰기 주의
spring.datasource.username=root
spring.datasource.password=simjunhyun1@
# 2-3 Entity 테이블 생성/수정, DDL : SQL정의어
# create : 서버실행할때마다 삭제후 생성
# update : 서버실행할때마다 존재하면 수정 존재하지않으면 생성
# none : 사용안한
spring.jpa.hibernate.ddl-auto=create

# 2-4 콘솔창에 실행된 sql표시
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# SQL내 매개변수 값들을 표시
logging.level.org.hibernate.jdbc.bind=TRACE
logging.level.org.hibernate.sql=DEBUG

# 2-5 서버 실행 할때 SQL파일 실행 * 개발 단계 *, always, none
spring.sql.init.mode=always
# 2-6 서버 실행 할때 classpath(resources폴더) 이하 에 data.sql
spring.sql.init.data-locations=classpath:/sql/data.sql
# 2-7 서버 실행 할때 JPA가 초기화 파일 실행
spring.jpa.defer-datasource-initialization=true